// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zefi.Telegram.Bot.TimeTracking.Db;

#nullable disable

namespace Zefi.Telegram.Bot.TimeTracking.Db.Migrations
{
    [DbContext(typeof(TTDbContext))]
    partial class TTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zefi.Telegram.Bot.TimeTracking.Db.Models.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TelegramUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("MessageTemplates");
                });

            modelBuilder.Entity("Zefi.Telegram.Bot.TimeTracking.Db.Models.TelegramUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TimeTrackingInfoId")
                        .HasColumnType("uuid");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TimeTrackingInfoId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("Zefi.Telegram.Bot.TimeTracking.Db.Models.TimeTrackingInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastHelloSend")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TimeTrackingInfos");
                });

            modelBuilder.Entity("Zefi.Telegram.Bot.TimeTracking.Db.Models.MessageTemplate", b =>
                {
                    b.HasOne("Zefi.Telegram.Bot.TimeTracking.Db.Models.TelegramUser", null)
                        .WithMany("MessageTemplatesList")
                        .HasForeignKey("TelegramUserId");
                });

            modelBuilder.Entity("Zefi.Telegram.Bot.TimeTracking.Db.Models.TelegramUser", b =>
                {
                    b.HasOne("Zefi.Telegram.Bot.TimeTracking.Db.Models.TimeTrackingInfo", "TimeTrackingInfo")
                        .WithMany()
                        .HasForeignKey("TimeTrackingInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeTrackingInfo");
                });

            modelBuilder.Entity("Zefi.Telegram.Bot.TimeTracking.Db.Models.TelegramUser", b =>
                {
                    b.Navigation("MessageTemplatesList");
                });
#pragma warning restore 612, 618
        }
    }
}
